name: trailing-stop-paper

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "*/10 13-20 * * 1-5"  # cada 10 min, lun-vie, 13:00–20:59 UTC aprox mercado

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run trailing stop
        env:
          APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
          APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
        run: |
          python trailing_5_8.py
