name: manage-stops-paper

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/2 13-20 * * 1-5"   # corre cada 2 minutos, lun-vie, 13:00–20:59 UTC (horario mercado USA aprox)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script (manage stops)
        env:
          APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
          APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
        run: |
          python ./manage_stops.py
